insert into person (id,name,email) values(1,'Ed','ed@ed.com')
insert into person (id,name,email) values(2,'Dave','dave@dave.com')
insert into person (id,name,email) values(3,'Bill','bill@bill.com')
insert into person (id,name,email) values(4,'Doug','doug@doug.com')
insert into message (id,content,sender_id) values(1,'Message 1',4)
insert into message (id,content,sender_id) values(2,'Message 2',3)
insert into message (id,content,sender_id) values(3,'Message 3',2)
insert into message (id,content,sender_id) values(4,'Message 4',1)
insert into message (id,content,sender_id) values(5,'Message 5',2)
insert into message (id,content,sender_id) values(6,'Message 6',2)
